"""Initial migration

Revision ID: fb4ade7deb20
Revises: 
Create Date: 2024-05-27 17:35:08.094486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb4ade7deb20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('approval_expiry', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('banca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('banca_inicial', sa.Float(), nullable=False),
    sa.Column('banca_total', sa.Float(), nullable=False),
    sa.Column('aportes', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aposta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=10), nullable=False),
    sa.Column('mandante', sa.String(length=100), nullable=False),
    sa.Column('visitante', sa.String(length=100), nullable=False),
    sa.Column('tipo_jogo', sa.String(length=100), nullable=False),
    sa.Column('confianca', sa.String(length=10), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('odd', sa.Float(), nullable=False),
    sa.Column('retorno', sa.Float(), nullable=False),
    sa.Column('resultado', sa.String(length=10), nullable=False),
    sa.Column('banca_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['banca_id'], ['banca.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aposta')
    op.drop_table('banca')
    op.drop_table('user')
    # ### end Alembic commands ###
